[build-system]
requires = ["meson-python"]
build-backend = "mesonpy"

[project]
name = "v-lczero-bindings"
version = "<version>"
description = "Leela Chess Zero Python bindings"
authors = [{ name = "The LCZero Authors" }]
license = {file = "COPYING"}
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Games/Entertainment :: Board Games",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]

[project.urls]
Homepage = "https://github.com/Xmaster6y/v-lczero-bindings"
Repository = "https://github.com/Xmaster6y/v-lczero-bindings"
Issues = "https://github.com/Xmaster6y/v-lczero-bindings/issues"

[tool.meson-python.args]
dist = []
setup = [
    "-Dpython_bindings=true",
    "-Dnative_arch=false",
    "-Dgtest=false",
]
compile = []
install = []
