name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"] # TODO: fix windows-latest build errors
    runs-on: ${{ matrix.os }}
    environment: publish
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - name: Setup build
      run: |
        bash setup.sh
      env:
        LC0_VERSION: ${{ inputs.version }}
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23.3
      with:
        package-dir: lc0
        output-dir: dist
      env:
        CIBW_BUILD: cp{310,311,312}-{macosx_arm64,manylinux_x86_64}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        uv build lc0 -o dist --sdist
    - name: Store assets
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ inputs.version }}-${{ strategy.job-index }}
        path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        pattern: package-${{ inputs.version }}-*
        merge-multiple: true
        path: dist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist
